# Generated by Django 3.2 on 2021-06-15 07:55

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('is_completed', django.db.models.expressions.OrderBy(django.db.models.expressions.F('deadline'), descending=True, nulls_last=True), 'created_at')},
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
